### ISSUE TITLE
When handling bloc errors, add a Chain from stack_trace

### ISSUE THREAD

**Issue by PlugFox** [PlugFox/bloc#1]
When handling bloc errors, add a [Chain](https://pub.dev/documentation/stack_trace/latest/stack_trace/Chain-class.html) from [stack_trace](https://pub.dev/packages/stack_trace)

**Comment by Aqluse** [comment]
It's not clear where it's going to be added

**Comment by PlugFox** [comment]
@Aqluse `_bindEventsToStates() and `onError()`

**Comment by PlugFox** [comment]
partially implemented
