### ISSUE TITLE
The BLoC should return a StateStream in stream getter

### ISSUE THREAD

**Issue by PlugFox** [PlugFox/bloc#11]
The BLoC should return a StateStream in stream getter.

Additional methods:

```dart
WhereState<T>()
WhereStates<T1,T2>()
WhereUnique<T>()
WhereUniques<T1,T2>()
```

**Comment by Aqluse** [comment]
I'd prefer it to be present up to 3 type generics in a default implementation and 4-9 in a separate extension for hardcore enjoyers

**Comment by zs-dima** [comment]
> 
> 
> 4-9 in a separate extension for hardcore enjoyers
Nice idea to move extra methods to the extension methods 
maybe could be better to move 3-9 to to the extension methods however

**Comment by PlugFox** [comment]
@Aqluse 

```dart
class Bloc<Event extends Object?, State extends Object?>
  extends IBloc<Event, State> {
  ...
  StateStream get stream => ...;
  ...
}
```

`StateStream ` is `StreamView` with additional helpers, like

```dart
.whereState<T>()
```

and

```dart
.whereUnique<T>()
```

you can upcast StateStream to Stream without losing the main functionality (LSP is SOLID)
