### ISSUE TITLE
Support question

### ISSUE THREAD

**Issue by leech001** [PlugFox/bloc#38]
Greetings. Please tell me if this project is planned for further support. The question is not even in terms of functional development, but in terms of keeping dependencies up to date?
I want to transfer a part of projects on this library and I am strongly afraid that it will be abandoned :(

**Comment by PlugFox** [comment]
I am using this library in my app.
Created for myself needs, not for aggressive promotion.
If you are missing something, contribute.
So far the library has reached the minimum required functionality and suits my needs.
I do other things.
